from datetime import datetime


class IntrusionRuleEngine:
    """
    M03 event rule engine.

    Detection != Event.

    Detection:
        AI observation of a person.

    Event:
        A temporally/spatially validated action.

    Incident:
        A reviewable platform-level record.
    """

    def __init__(self, config: dict):
        self.config = config

        event_config = config["event"]

        self.minimum_frames = int(
            event_config["minimum_frames"]
        )

        self.loitering_seconds = float(
            event_config["loitering_seconds"]
        )

        self.cooldown_seconds = float(
            event_config["cooldown_seconds"]
        )

        # ------------------------------------------------------
        # Unique event sequence
        # ------------------------------------------------------
        #
        # The previous implementation generated event IDs
        # using only:
        #
        #     camera_id + frame_id + track_id
        #
        # This could cause collisions when two different event
        # types were generated for the same person on the same
        # frame.
        #
        # Example:
        #
        #   Zone Entry -> EVT-CAM-001-152-20
        #   Loitering  -> EVT-CAM-001-152-20
        #
        # The sequence number guarantees uniqueness for every
        # event generated by this rule engine instance.
        #
        self.event_sequence = 0

        # Restricted-zone state
        self.zone_states = {}

        # Restricted-zone event cooldown
        self.last_events = {}

        # Tripwire event cooldown
        #
        # Key:
        #   camera_id + track_id + tripwire_name
        #
        # This prevents the same tracked person from
        # generating repeated tripwire events within
        # the configured cooldown period.
        self.last_tripwire_events = {}

    # ==========================================================
    # RESTRICTED ZONE
    # ==========================================================

    def check_detection(
        self,
        detection: dict,
        current_time=None,
    ):
        if current_time is None:
            current_time = datetime.now()

        events = []

        track_id = detection.get(
            "track_id"
        )

        if track_id is None:
            return events

        camera_id = detection["camera_id"]

        point = self._bottom_center(
            detection["bbox"]
        )

        zone_config = self.config.get(
            "zones",
            {}
        )

        restricted_zones = zone_config.get(
            "restricted_zones",
            []
        )

        for zone in restricted_zones:

            zone_name = zone.get(
                "name",
                "Restricted Zone"
            )

            polygon = zone.get(
                "polygon",
                []
            )

            if len(polygon) < 3:
                continue

            inside = self._point_in_polygon(
                point,
                polygon
            )

            state_key = (
                camera_id,
                track_id,
                zone_name,
            )

            previous_state = self.zone_states.get(
                state_key,
                {
                    "inside": False,
                    "entered_at": None,
                    "frames_inside": 0,
                }
            )

            if inside:

                previous_state[
                    "frames_inside"
                ] += 1

                if not previous_state["inside"]:

                    previous_state[
                        "inside"
                    ] = True

                    previous_state[
                        "entered_at"
                    ] = current_time

                if (
                    previous_state[
                        "frames_inside"
                    ]
                    >= self.minimum_frames
                ):

                    if self._is_restricted_time(
                        current_time
                    ):

                        if self._cooldown_expired(
                            state_key,
                            current_time
                        ):

                            events.append(
                                self._create_event(
                                    detection=detection,
                                    event_type=(
                                        "POTENTIAL_UNAUTHORIZED_ZONE_ENTRY"
                                    ),
                                    severity="HIGH",
                                    timestamp=current_time,
                                    zone_name=zone_name,
                                )
                            )

                            self.last_events[
                                state_key
                            ] = current_time

                entered_at = (
                    previous_state.get(
                        "entered_at"
                    )
                )

                if entered_at is not None:

                    elapsed = (
                        current_time
                        - entered_at
                    ).total_seconds()

                    if (
                        elapsed
                        >= self.loitering_seconds
                    ):

                        loiter_key = (
                            f"{state_key}_loiter"
                        )

                        if self._cooldown_expired(
                            loiter_key,
                            current_time
                        ):

                            events.append(
                                self._create_event(
                                    detection=detection,
                                    event_type="LOITERING",
                                    severity="MEDIUM",
                                    timestamp=current_time,
                                    zone_name=zone_name,
                                )
                            )

                            self.last_events[
                                loiter_key
                            ] = current_time

            else:

                previous_state[
                    "inside"
                ] = False

                previous_state[
                    "entered_at"
                ] = None

                previous_state[
                    "frames_inside"
                ] = 0

            self.zone_states[
                state_key
            ] = previous_state

        return events

    # ==========================================================
    # TRIPWIRE
    # ==========================================================

    def check_tripwires(
        self,
        previous_detection,
        current_detection: dict,
        current_time=None,
    ):
        """
        Detect whether a tracked person crossed
        a configured virtual tripwire.

        The movement is determined using the bottom-center
        point of the person's bounding box.

        Direction is calculated relative to the configured
        tripwire orientation:

            Point A --------------> Point B

        Possible directions:

            A_TO_B
            B_TO_A
            UNKNOWN

        Deduplication:
            The same camera + track + tripwire cannot
            generate another tripwire event until the
            configured cooldown period has expired.
        """

        if current_time is None:
            current_time = datetime.now()

        if previous_detection is None:
            return []

        track_id = current_detection.get(
            "track_id"
        )

        if track_id is None:
            return []

        camera_id = current_detection[
            "camera_id"
        ]

        previous_point = self._bottom_center(
            previous_detection["bbox"]
        )

        current_point = self._bottom_center(
            current_detection["bbox"]
        )

        tripwires = (
            self.config
            .get("zones", {})
            .get("tripwires", [])
        )

        events = []

        for tripwire in tripwires:

            name = tripwire.get(
                "name",
                "Restricted Line"
            )

            line = tripwire.get(
                "line",
                []
            )

            if len(line) != 2:
                continue

            point_a = tuple(
                line[0]
            )

            point_b = tuple(
                line[1]
            )

            crossed = self._segments_intersect(
                previous_point,
                current_point,
                point_a,
                point_b,
            )

            if not crossed:
                continue

            # --------------------------------------------------
            # Tripwire cooldown / deduplication
            # --------------------------------------------------

            cooldown_key = (
                camera_id,
                track_id,
                name,
            )

            if not self._cooldown_expired(
                cooldown_key,
                current_time,
                self.last_tripwire_events,
            ):
                continue

            direction = (
                self._calculate_direction(
                    previous_point,
                    current_point,
                    line,
                )
            )

            event = self._create_event(
                detection=current_detection,
                event_type="TRIPWIRE_CROSSED",
                severity="HIGH",
                timestamp=current_time,
                zone_name=name,
                direction=direction,
            )

            events.append(event)

            # Record the time of the generated
            # tripwire event.
            self.last_tripwire_events[
                cooldown_key
            ] = current_time

        return events

    # ==========================================================
    # SCHEDULE
    # ==========================================================

    def _is_restricted_time(
        self,
        current_time: datetime,
    ):

        schedule = self.config.get(
            "schedule",
            {}
        )

        if not schedule.get(
            "enabled",
            False
        ):
            return True

        start_text = str(
            schedule["restricted_start"]
        )

        end_text = str(
            schedule["restricted_end"]
        )

        start = datetime.strptime(
            start_text,
            "%H:%M"
        ).time()

        end = datetime.strptime(
            end_text,
            "%H:%M"
        ).time()

        current = current_time.time()

        if start <= end:

            return (
                start
                <= current
                <= end
            )

        return (
            current >= start
            or current <= end
        )

    # ==========================================================
    # COOLDOWN
    # ==========================================================

    def _cooldown_expired(
        self,
        key,
        current_time: datetime,
        event_store=None,
    ):
        """
        Check whether the configured cooldown period
        has expired for a particular event key.

        event_store can be supplied for separate event
        categories such as tripwires.
        """

        if event_store is None:
            event_store = self.last_events

        previous = event_store.get(
            key
        )

        if previous is None:
            return True

        elapsed = (
            current_time - previous
        ).total_seconds()

        return (
            elapsed
            >= self.cooldown_seconds
        )

    # ==========================================================
    # GEOMETRY
    # ==========================================================

    @staticmethod
    def _bottom_center(bbox):

        x1 = bbox["x1"]
        y1 = bbox["y1"]
        x2 = bbox["x2"]
        y2 = bbox["y2"]

        return (
            (x1 + x2) / 2,
            y2,
        )

    @staticmethod
    def _point_in_polygon(
        point,
        polygon,
    ):

        x, y = point

        inside = False

        j = len(polygon) - 1

        for i in range(
            len(polygon)
        ):

            xi, yi = polygon[i]
            xj, yj = polygon[j]

            intersects = (
                (yi > y)
                != (yj > y)
                and
                x
                <
                (
                    (xj - xi)
                    * (y - yi)
                    / ((yj - yi) or 1e-9)
                    + xi
                )
            )

            if intersects:
                inside = not inside

            j = i

        return inside

    @staticmethod
    def _orientation(
        a,
        b,
        c,
    ):

        value = (
            (b[1] - a[1])
            * (c[0] - b[0])
            -
            (b[0] - a[0])
            * (c[1] - b[1])
        )

        if abs(value) < 1e-9:
            return 0

        if value > 0:
            return 1

        return 2

    @staticmethod
    def _on_segment(
        a,
        b,
        c,
    ):

        return (
            min(a[0], c[0])
            <= b[0]
            <= max(a[0], c[0])
            and
            min(a[1], c[1])
            <= b[1]
            <= max(a[1], c[1])
        )

    @classmethod
    def _segments_intersect(
        cls,
        p1,
        q1,
        p2,
        q2,
    ):

        o1 = cls._orientation(
            p1,
            q1,
            p2
        )

        o2 = cls._orientation(
            p1,
            q1,
            q2
        )

        o3 = cls._orientation(
            p2,
            q2,
            p1
        )

        o4 = cls._orientation(
            p2,
            q2,
            q1
        )

        if (
            o1 != o2
            and o3 != o4
        ):
            return True

        if (
            o1 == 0
            and cls._on_segment(
                p1,
                p2,
                q1
            )
        ):
            return True

        if (
            o2 == 0
            and cls._on_segment(
                p1,
                q2,
                q1
            )
        ):
            return True

        if (
            o3 == 0
            and cls._on_segment(
                p2,
                p1,
                q2
            )
        ):
            return True

        if (
            o4 == 0
            and cls._on_segment(
                p2,
                q1,
                q2
            )
        ):
            return True

        return False

    @staticmethod
    def _calculate_direction(
        previous_point,
        current_point,
        line,
    ):

        line_a = (
            float(line[0][0]),
            float(line[0][1])
        )

        line_b = (
            float(line[1][0]),
            float(line[1][1])
        )

        movement_x = (
            current_point[0]
            - previous_point[0]
        )

        movement_y = (
            current_point[1]
            - previous_point[1]
        )

        line_x = (
            line_b[0]
            - line_a[0]
        )

        line_y = (
            line_b[1]
            - line_a[1]
        )

        dot_product = (
            movement_x * line_x
            +
            movement_y * line_y
        )

        if abs(dot_product) < 1e-9:
            return "UNKNOWN"

        if dot_product > 0:
            return "A_TO_B"

        return "B_TO_A"

    # ==========================================================
    # EVENT CREATION
    # ==========================================================

    def _create_event(
        self,
        detection,
        event_type,
        severity,
        timestamp,
        zone_name,
        direction=None,
    ):
        """
        Create a unique event record.

        Every generated event receives a monotonically
        increasing sequence number. This prevents collisions
        when multiple event types occur for the same camera,
        frame, and tracked person.

        Example:

            EVT-CAM-001-152-20-1
            EVT-CAM-001-152-20-2

        Even if both events belong to the same frame and
        track, their IDs remain unique.
        """

        self.event_sequence += 1

        event_id = (
            f"EVT-{detection['camera_id']}-"
            f"{detection['frame_id']}-"
            f"{detection.get('track_id', 'NA')}-"
            f"{self.event_sequence}"
        )

        event = {
            "event_id": event_id,
            "module": "module_03_intrusion",
            "event_type": event_type,
            "camera_id": detection[
                "camera_id"
            ],
            "track_id": detection.get(
                "track_id"
            ),
            "timestamp": timestamp.isoformat(),
            "confidence": detection[
                "confidence"
            ],
            "severity": severity,
            "status": "PENDING",
            "zone_name": zone_name,
        }

        if direction is not None:
            event["direction"] = direction

        return event